@startmindmap
skinparam handwritten true
* Paradigmas de Programación

**[#Orange] Funcional (Haskell)
*** 1.2.1 Evaluaciones
**** Perezosa (Lazy)
**** Ansiosa (Strict)
**** Transparencia Referencial
*** 1.2.2 Tipos de Datos
**** Inmutables
**** Primitivos (Int, Bool)
**** ADTs (Algebraicos)
**** Listas y Tuplas
*** 1.2.3 Disciplina de Tipos
**** Estático y Fuerte
**** Inferencia de Tipos
**** Polimorfismo
*** 1.2.4 Funciones
**** Ciudadanos de 1ra Clase
**** Puras
**** Orden Superior
**** Currying / Recursividad

**[#LightBlue] Lógico (Prolog)
*** 1.2.1 Evaluaciones
**** Unificación
**** Backtracking (Vuelta atrás)
**** Resolución SLD
*** 1.2.2 Tipos de Datos
**** Términos
**** Átomos (minúsculas)
**** Variables (Mayúsculas)
**** Estructuras
*** 1.2.3 Disciplina de Tipos
**** Dinámico
**** Verificación en ejecución
**** Sin declaración explícita
*** 1.2.4 Funciones (Predicados)
**** Relaciones (No funciones)
**** Retorno: Éxito / Fallo
**** Multidireccionalidad
@endmindmap